package dao;

public interface Procedure {

	String GET_DB_HOSTING = "{CALL GET_DB_HOSTING(?)}";
	String GET_URL_SOURCE = "{CALL GET_URL_SOURCE(?)}";
	String GET_PATH_FOLDER = "{CALL GET_PATH_FOLDER(?)}";
	String GET_DIST_FOLDER = "{CALL GET_DIST_FOLDER(?)}";

	String GET_FTP_HOSTING = "{CALL GET_FTP_HOSTING(?)}";

	// process1
	String GET_ONE_ROW_FROM_LOG = "{CALL GET_ONE_ROW_FROM_LOG(?)}";
	String INSERT_RECORD = "{CALL INSERT_RECORD(?,?)}";
	String UPDATE_STATUS = "{CALL UPDATE_STATUS(?,?)}";
	String UPDATE_TIME_LOAD = "{CALL UPDATE_TIME_LOAD(?,?)}";

	// process2
	String GET_ONE_FILE_IN_FTP = "{CALL GET_ONE_FILE_IN_FTP(?)}";
	String LOAD_THOI_TIET_EDU_VN_INTO_STAGING= "{CALL LOAD_THOI_TIET_EDU_VN_INTO_STAGING(?,?,?,?,?,?,?,?,?,?,?,?,?,?)}";
	String LOAD_THOI_TIET_VN_INTO_STAGING = "{CALL LOAD_THOI_TIET_VN_INTO_STAGING(?,?,?,?,?,?,?,?,?,?,?,?,?,?)}";
	String LOAD_WEATHER_DATA = "{CALL LOAD_WEATHER_DATA ()}";
	String TRANSFORM_WEATHER_FACT = "{CALL TRANSFORM_WEATHER_FACT(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)}";
	
	
//	String FINISH_LOAD_WEATHER_DATA_INTO_STAGING = "{CALL FINISH_LOAD_WEATHER_DATA_INTO_STAGING(?,?)}";
	String CHECK_DATE_DIM_IS_EXISTED = "{CALL CHECK_DATE_DIM_IS_EXISTED()}";
	String CHECK_TIME_DIM_IS_EXISTED = "{CALL CHECK_TIME_DIM_IS_EXISTED()}";
	String LOAD_DATE_DIM = "{CALL LOAD_DATE_DIM(?,?,?,?,?,?)}";
	String LOAD_TIME_DIM = "{CALL LOAD_TIME_DIM(?,?)}";
	String LOAD_PROVINCE_DIM = "{CALL LOAD_PROVINCE_DIM(?,?)}";

}
